### ISSUE TITLE
pass variables via command line

### ISSUE THREAD

**Issue by matey-jack** [restcli/restcli#20]
Thanks for making this tool! I have waited for it many months!

Since the recommendation for environment files is to not commit the private one into source control, this file will not be available when running tests on a CI server.

Possible solutions:

- somehow create that file in a script to be run before the test, which pulls the secrets from a secret store. (Creating the file with just the one environment entry to be run would be sufficient, but that's still some extra syntax to wrap around the secrets. So I am looking for a simpler way.)
- pass the secrets via command line to the runner (Command line may get long, when there are many secrets, but that's usually not the case.)
- pass the secrets via environment variables to the runner (can lead to very unexpected behavior when a variable in the .http file is overwritten by an env variable whose existence one wasn't aware of!)

In Gitlab CI, for example, secrets can be made available via environment variables. Then could then be passed to the tests like this:
`java -jar restcli.jar -Dapi-password=$API_PASSWORD my-api-test.http`

An additional advantage of this method is that also non-private variables can be set without having to modify the `http-client.env.json` file.

((I proposed the `-D` parameter here in analogy to passing Java System properties, so it's easy to remember. Although it might also be confusing. So maybe `-G` (for global variable) or `-P` (for private variable) should be used instead.))

As a bonus requirement, it would be awesome, if private variables would be omitted from any reports. ;-)

What do you think about it?

**Comment by quangson91** [comment]
Hi @matey-jack 
Firstly, Thank you for your suggestion.

I would like 💯  agreed with your idea.

For passing environments via command-line argument -> no problem.
The extra feature
> if private variables would be omitted from any reports.

 may take more time to implement. (I will research the solution for this problem. As I know, the github action CI also show private secret key in the console as `***`).

So I will try to implement passing env variables via command-line arguments first.

Thank you!

**Comment by quangson91** [comment]
@all-contributors please add @matey-jack for ideas

**Comment by quangson91** [comment]
Done in https://github.com/restcli/restcli/releases/tag/v1.7.0
