### ISSUE TITLE
Build docker image for rest-cli

### ISSUE THREAD

**Issue by quangson91** [restcli/restcli#21]
Create a docker image with support rest cli by default.

Eg: Make an alias in docker image. So instead call `java -jar rest-cli.jar` 
we just need `restcli .... arguments ....`

**Comment by xargon180** [comment]
@quangson91 Hi QuangSon can i support you with this issue?

**Comment by quangson91** [comment]
Yup. You can creat a Pull Request to this repo.

**Comment by xargon180** [comment]
PR is created.

**Comment by quangson91** [comment]
Yup. that great.
I merged that PR.
