### ISSUE TITLE
Create an executor using node/javascript

### ISSUE THREAD

**Issue by quangson91** [restcli/restcli#35]
By using node/javascript executor we can easily remove the dependency of nashorn engine.
Also, we can using latest feature of the new javascript version.

Intent:
- restcli: For parser
- easy to create custom executor in other languages(currently the executor is using nashron engine).

**Comment by npeters** [comment]
may be Graalvm should be a other option: Graalvm include the capability to run some javascript   https://www.graalvm.org/reference-manual/js/ and it will give you the possibly to build a native image

**Comment by quangson91** [comment]
Yup. I'm trying to use graalvm in this project.
Thx!

**Comment by npeters** [comment]
I can help on this topic, if you need !

**Comment by quangson91** [comment]
Yup.  I will try to implement then we can disscuss based on the pull request.

**Comment by npeters** [comment]
Ok, cool !

**Comment by quangson91** [comment]
Done in https://github.com/restcli/restcli/commit/9f989989a45c5691f7a21e6204cbe60233539b0f
