### ISSUE TITLE
Wrong parameter substitution in url

### ISSUE THREAD

**Issue by pil0t** [restcli/restcli#37]
I have request in .http file with URL defined as:
`GET {{host}}/v1/people?$filter=groupId eq+ {{groupId}}`
in Rider (similar HTTP Client) I can see in the output real URL as:
`GET http://localhost/v1/people?%24filter=groupId+eq+bad0680d-4f5b-4739-8739-3233bd8ef8fa`
In the restcli I can see next:
```##### GET bad0680d-4f5b-4739-8739-3233bd8ef8fa #####
--> GET http://bad0680d-4f5b-4739-8739-3233bd8ef8fa/
--> END GET```

**Comment by quangson91** [comment]
Currently, the parse doesn't support the `space` character in the target url. (I will implement it later).
For now, please try to escapse the space in the url. (I will check this more in the IDE).

**Comment by quangson91** [comment]
Fixed in https://github.com/restcli/restcli/releases/tag/v1.7.3

**Comment by quangson91** [comment]
@all-contributors please add @pil0t  for userTesting
