### ISSUE TITLE
[Bug] Test results format incompatible with bitbucket pipelines

### ISSUE THREAD

**Issue by pil0t** [restcli/restcli#54]
I used restcli to execute tests as part of bitbucket pipeline, and found that bitbucket didn't understand results correctly.
I created request to support, and they respond me:
 

> Test report being generated as the following:
> ```
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <testsuites tests="2" name="IntelliJ Rest CLI - Test Generator">
> <testsuite tests="1" name="https://bitbucket.org/"><testcase name="Request executed successfully"/>
> </testsuite><testsuite tests="1" name="https://api.bitbucket.org/notexist">                <testcase name="Request executed successfully">
>                     <failure type="AssertionFailure">Response status is not 200
> File: example.http
> Line: 14</failure>
>                 </testcase>
> </testsuite></testsuites>
> ```
> 
> 
> To get it working, format should be adjusted to:
> ```
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <testsuites tests="2" name="IntelliJ Rest CLI - Test Generator">
> 	<testsuite tests="1" name="https://bitbucket.org/" errors="0" failures="0" skip="0">
> 		<testcase classname="Test" name="Request executed successfully" time="0">
> 		</testcase>
> 	</testsuite>
> 	<testsuite tests="1" name="https://api.bitbucket.org/notexist" errors="0" failures="1" skip="0">
> 		<testcase classname="Test" name="Request executed successfully" time="0">
> 			<failure type="AssertionFailure" message="Response status is not 200">
> 			File: example.http
> 			Line: 14
> 			</failure>
> 		</testcase>
> 	</testsuite>
> </testsuites>
> ```
> We suspect that your reporting tool is not following the X-Unit / J-Unit format, because as you can see certain parameters are missing.

**Comment by quangson91** [comment]
Thank you for reporting the issue and create the PR.
I merged your PR.
and I will release new version soon.
Thank you!
