### ISSUE TITLE
Node docker image for CI build

### ISSUE THREAD

**Issue by J4YF7O** [restcli/restcli#75]
Hello there, 

I discovered the project this W.E. First of all, thank you for everything! 

I am developing api in NodeJS. To test it I need to run restcli in a gitlab CI. 
That's why I propose this docker image :  [restcli-node](https://hub.docker.com/repository/docker/j4yf7o/restcli-node)

Is base on a "node" image, with the openjdk installed, and a command to execute "restcli" (rest-cli). 

I'm open to your suggestions, modifications, or simply to your critics.

More on [github](https://github.com/J4YF7O/restcli-node)

(A javascript version of the code as proposed on #35  would allow to only have to install the package, without having to go through all that)

With pleasure
J4Y

**Comment by quangson91** [comment]
That is a cool project. I will add the reference to your repo. So that may help some nodejs developers.
Thank you!
