### ISSUE TITLE
Preserve variables between files

### ISSUE THREAD

**Issue by mkczyk** [restcli/restcli#90]
When I set variable in first request and use it in the same file it works. But if I set variable in one file and use it in another it doesn't work. In IntelliJ Http Client it works.

## Example with one file (works in IntelliJ HTTP Client and also in REST CLI)

`example.http`:
```
### Test a
GET https://httpbin.org/uuid

> {%
client.test("Request executed successfully", function() {
  client.log("response body: " + response.body.uuid);
  client.global.set("my_variable", response.body.uuid);
});
%}

### Test b
GET https://httpbin.org/get?show={{my_variable}}

> {%
client.test("Request executed successfully", function() {
  client.log("my_variable: " + client.global.get("my_variable"));
});
%}
```

**IntelliJ:**

First request:

![image](https://user-images.githubusercontent.com/11051213/147614886-4a546fbd-a888-420b-aab4-198162a3b170.png)

Second request: 

![image](https://user-images.githubusercontent.com/11051213/147614908-7a4d0bda-1804-471a-8b8c-d479f3727f75.png)

![image](https://user-images.githubusercontent.com/11051213/147614928-132c29c7-fb03-4760-a704-4e7156766e34.png)

**REST CLI:**

```
java -jar restcli.jar example.http
```

First request: 

![image](https://user-images.githubusercontent.com/11051213/147615017-83b2245e-8792-4296-a72b-da7499a80d7b.png)

Second request: 

![image](https://user-images.githubusercontent.com/11051213/147615029-e15fb551-db9f-4000-83e6-825a5b078707.png)

## Example with two files (works in IntelliJ HTTP Client but doesn't work in REST CLI)

`example1.http`:
```
### Test a
GET https://httpbin.org/uuid

> {%
client.test("Request executed successfully", function() {
  client.log("response body: " + response.body.uuid);
  client.global.set("my_variable", response.body.uuid);
});
%}
```

`example2.http`:
```
### Test b
GET https://httpbin.org/get?show={{my_variable}}

> {%
client.test("Request executed successfully", function() {
  client.log("my_variable: " + client.global.get("my_variable"));
});
%}
```

**IntelliJ:**

First request:

![image](https://user-images.githubusercontent.com/11051213/147615110-b03c79d1-e2f8-43d2-9e67-06e6b1b4c90b.png)

Second request:

![image](https://user-images.githubusercontent.com/11051213/147615132-008af849-0037-4b45-878d-77b4e75eb8db.png)

![image](https://user-images.githubusercontent.com/11051213/147615137-f7d5c957-be93-48be-b7f9-0efa7b7adffc.png)

**REST CLI:**

```
java -jar restcli.jar example1.http
java -jar restcli.jar example2.http
```

First request: 

![image](https://user-images.githubusercontent.com/11051213/147615209-fd74bee4-ebec-4e64-9e79-c76effcb8374.png)

Second request:

![image](https://user-images.githubusercontent.com/11051213/147615234-07c9475a-55c8-4357-941a-8776040da89d.png)

You can see that variable isn't existed:

```
WARNING: Define my_variable but there is no define in environment

"{{my_variable}}"

my_variable: undefined
```

I know these are two separated invoking REST CLI. But how to share variables between them like in IntelliJ HTTP Client? Maybe there is a way to run two files at once or configure temp file to preserve variables?

**Comment by quangson91** [comment]
Hi @mkczyk,
Yes, there is a way to run multiple files.
You can try to run:

```sh
java -jar restcli.jar example1.http example2.http
```

Then in the test in the file `example2.http` you can re-use the variables from the `example1.http`.

**Comment by quangson91** [comment]
@mkczyk 
If the above comment doesn't resolve the issue, feel free to re-open this issue.
Thanks!
